#服务配置
server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /template

spring:
  #数据库配置
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_SCHEME}?useUnicode=true&zeroDateTimeBehavior=convertToNull&amp;characterEncoding=UTF-8
    #阿里druid连接池驱动配置信息
    type: com.alibaba.druid.pool.DruidDataSource
    #连接池的配置信息
    druid:
      #初始化大小，最小，最大
      initial-size: 2

  #redis配置
#  redis:
#    host: ${REDIS_HOST}
#    port: ${REDIS_PORT}
#    password:
#    timeout: 10000
#    maxTotal: 8

#udp配置



mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  not-empty: true
  identity: MYSQL
  style: normal
  wrap-keyword: "`{0}`"

custom:
  env: ${ENV}


